import Head from 'next/head'

import Header from '../components/Header'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <main className="px-28 text-[#100d47]">
        <Header></Header>
        <div className="w-full flex gap-10">
          <div className="h-fit w-full">
              <h1 className="leading-normal text-7xl font-bold">Wherever you are, we can help you move forward.</h1>
              <p className="leading-loose">Omahku has been bringing buyers and sellers together since 1996 by providing them with the simplest and most cost-effective rout to selling or buying properties online.</p>
              <div className='flex mt-8'>
                <button className="mr-8 bg-none border border-[#100d47] hover:bg-blue-700 py-4 px-14 rounded-xl">Get Started</button>
                <button className="bg-[#100d47] hover:bg-blue-700 text-white py-4 px-14 rounded-xl">Introduction</button>
              </div>
              <div className="flex gap-10 mt-10">
                <div className="h-20 w-full flex items-center gap-3">
                  <span className="text-6xl font-bold">2.7K</span>
                  <p className="w-0">Properties Sold</p>
                </div>
                <div className="h-20 w-full flex items-center gap-3">
                  <span className="text-6xl font-bold">9.1M</span>
                  <p className="w-24">Satisfied and Happy Users</p>
                </div>
              </div>
          </div>
          <div className="bg-red-500 h-5/5 w-full flex justify-center items-center">
            <p>Graphic Here</p>
          </div>
        </div>
      </main>
    </div>
  )
}
